/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CirclesRouteImport } from './routes/circles'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CirclesCircleIdRouteImport } from './routes/circles.$circleId'

const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesRoute = CirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesCircleIdRoute = CirclesCircleIdRouteImport.update({
  id: '/$circleId',
  path: '/$circleId',
  getParentRoute: () => CirclesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/circles': typeof CirclesRouteWithChildren
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/workout': typeof WorkoutRoute
  '/circles/$circleId': typeof CirclesCircleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/circles': typeof CirclesRouteWithChildren
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/workout': typeof WorkoutRoute
  '/circles/$circleId': typeof CirclesCircleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/circles': typeof CirclesRouteWithChildren
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/workout': typeof WorkoutRoute
  '/circles/$circleId': typeof CirclesCircleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/circles'
    | '/coach'
    | '/dashboard'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/workout'
    | '/circles/$circleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/circles'
    | '/coach'
    | '/dashboard'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/workout'
    | '/circles/$circleId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/circles'
    | '/coach'
    | '/dashboard'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/workout'
    | '/circles/$circleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CirclesRoute: typeof CirclesRouteWithChildren
  CoachRoute: typeof CoachRoute
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  WorkoutRoute: typeof WorkoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles': {
      id: '/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof CirclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles/$circleId': {
      id: '/circles/$circleId'
      path: '/$circleId'
      fullPath: '/circles/$circleId'
      preLoaderRoute: typeof CirclesCircleIdRouteImport
      parentRoute: typeof CirclesRoute
    }
  }
}

interface CirclesRouteChildren {
  CirclesCircleIdRoute: typeof CirclesCircleIdRoute
}

const CirclesRouteChildren: CirclesRouteChildren = {
  CirclesCircleIdRoute: CirclesCircleIdRoute,
}

const CirclesRouteWithChildren =
  CirclesRoute._addFileChildren(CirclesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CirclesRoute: CirclesRouteWithChildren,
  CoachRoute: CoachRoute,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  WorkoutRoute: WorkoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
